Add : 상품 상세 정보 API & 커피 필터링, 정렬 API 작성
wecode-bootcamp-korea/13-coderoasters-backend pull request #2
Opened 2020-11-05 08:40 UTC by mgm-dev

### 상품 상세 정보 API
- route : /products/:product_id
- products / coffees / equipments 테이블에서 정보 조회

### 커피 필터링, 정렬 API 작성
- route : /products/coffees?filter_category[]=filter+option&order_by=price
- 필터 카테고리별 중첩 필터링 기능
- 가격 / 인기 / 날짜 별 정릴 기능

2020-11-06 09:49 UTC, Jun4928 requested changes
경민님 로직 훌륭합니다!

2020-11-06 09:49 UTC, Jun4928 commented on controllers/ProductController.js
> +
Controller 안에 정의된 함수의 이름이 현재 모두 다 명사형 입니다.
**동사형**으로 바꿔주세요

- `getProductDetail`
- `getCoffeeList`
...

2020-11-06 09:49 UTC, Jun4928 commented on controllers/ProductController.js
> +    const query = req.query
```js
const { query } = req
```

2020-11-06 09:49 UTC, Jun4928 commented on controllers/ProductController.js
> +    const foundProduct = await ProductService.findProduct(req.params.productId)
params 그냥 넣지 마시고
상단에서 구조분해 할당해서 넣어주세요.

2020-11-06 09:49 UTC, Jun4928 commented on routes/ProductRouter.js
> +router.get('/:productId', ProductController.productDetail)
Controller 에 함수의 이름이 바뀌면
여기도 연결해주는 미들웨어의 이름이 바뀌어야 겠죠?

2020-11-06 09:49 UTC, Jun4928 commented on services/ProductService.js
> +    take: 18,
1. offset 하드코딩 하지 마시고 상단에 상수로 빼서 관리해 주세요
2. query.page 가 String 으로 들어와도 숫자와 연산이 되면 Number 타입으로 바뀝니다. 
하지만 연산중에 형변환 하는 코드는 안전한 코드라고 할 수 없습니다. 

다음과 같은 코드가 의도를 드러내기에 더 좋은 것 같습니다.
```js
const OFFSET = 18

skip: query.page ? (Number(query.page) - 1 * OFFSET) : 0 
```

2020-11-06 09:49 UTC, Jun4928 commented on services/ProductService.js
> +    })
여기도 coffee 와 roaster 가 관계성이 있는 데이터기 때문에 하나의 findOne 으로 roaster 를 찾아오는 것이 좋습니다.
```js
const coffee = await prisma.coffees.findOne({
  where: { product_id: Number(productId) },
  include: {
    roasters: true
  }
})
```

2020-11-06 09:49 UTC, Jun4928 commented on services/ProductService.js
> +  }
else 문 말고
`if (foundProduct.product_type === 'equipment')` 로 처리 해 주세요.
물론 ENUM 타입에 두개밖에 없어서 `if / else` 문을 통해서 로직 처리 할 수 있지만

추후에 확장성을 고려하면 if 의 연속이 좋습니다. 
그리고 정확한 타입 체킹을 하는 것이 안전합니다.

2020-11-06 09:49 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +    delete obj.page
함수로 들어오는 인자를 변경하는 코드는 좋지 않습니다. 함수의 순수성에 어긋납니다.
해당 Key 값들을 배제하는 객체를 얻고 싶으면 다음과 같은 코드를 사용하세요.
```js
const {order_by, page, ...modifiedObj} = obj
```

2020-11-06 09:49 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +    for (let key in obj) {
```js
for (const key in obj)
```

2020-11-06 09:49 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +      returnObj['AND'].push({ OR: orArray })
1. orArray 를 얻어내는 이 로직을 함수로 분리하세요. 함수의 인자에 객체와 키값을 넘겨주면 되겠죠!

2. 그리고 switch 문 사용하지 마세요.
```js
const PRICE_OPTION = {
  1: { lt: 15 },
  2: { gte: 15, lt: 18},
  3: { gte: 18, lt: 22},
  4: { gte: 22}
}

const orArray = obj[key].map((bucketId) => {
  return { price: PRICE_OPTION[bucketId] }  
})

```

2020-11-06 09:49 UTC, Jun4928 commented on utils/makeDataForSort.js
> +        return { orderBy: { sales_amount: 'desc' } }
여기도 switch 문 말고
객체 활용하세요!

2020-11-06 14:05 UTC, mgm-dev commented on controllers/ProductController.js
> +
함수명에 get 추가했습니다 :)

2020-11-06 14:17 UTC, mgm-dev commented on controllers/ProductController.js
> +    const foundProduct = await ProductService.findProduct(req.params.productId)
구조분해 할당 하는 것이 확정성이 더 좋겠네요!

2020-11-06 14:17 UTC, mgm-dev commented on controllers/ProductController.js
> +    const query = req.query
수정했습니다 :)

2020-11-06 14:18 UTC, mgm-dev commented on routes/ProductRouter.js
> +router.get('/:productId', ProductController.productDetail)
get 추가했습니다!

2020-11-06 14:20 UTC, mgm-dev commented on services/ProductService.js
> +    take: 18,
OFFSET 상수화하고 형변환 하는 지점 변경했습니다 :)

2020-11-06 14:20 UTC, mgm-dev commented on services/ProductService.js
> +    })
findOne에서 한번에 가져오게 수정했습니다.

2020-11-06 14:21 UTC, mgm-dev commented on services/ProductService.js
> +  }
equipment 타입 체크하게 수정했습니다 :)

2020-11-06 14:22 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +    delete obj.page
이렇게도 구조분해할당 할 수 있다는 것 처음 알았습니다!

2020-11-06 14:22 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +    for (let key in obj) {
const로 수정했습니다.

2020-11-06 14:23 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +      returnObj['AND'].push({ OR: orArray })
수정했습니다! switch 보다 훨씬 간결하고 보기 좋은 것 같아요 :)

2020-11-06 14:23 UTC, mgm-dev commented on utils/makeDataForSort.js
> +        return { orderBy: { sales_amount: 'desc' } }
수정했습니다! switch 보다 훨씬 간결하고 보기 좋은 것 같아요 :)

2020-11-07 13:24 UTC, Jun4928 requested changes

2020-11-07 13:24 UTC, Jun4928 commented on services/ProductService.js
> +  if (foundProduct.product_type === 'equipment') {
다른 로직 사이에는 빈 줄 넣어주세요 🙌

2020-11-07 13:24 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +    }
GOOD

2020-11-07 13:24 UTC, Jun4928 commented on utils/makeDataForSort.js
> +}
GOOD!

2020-11-07 13:24 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +  const numberRgx = /^\d+(\.\d+)?$/
숫자 가려내는 정규표현식이 현재는 이 함수에서만 사용될 수 있지만,
만약 다른 유틸함수나 서비스 로직에서 사용될 수 있다면요?

이것도 모듈화 해서 관리 해 보세요 👍

2020-11-07 13:24 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +  }
else 문이 꼭 필요할까요?
key 값이 price_bucket 이 아니면 무조건 아래 로직이 처리 됩니다. 

```js
// 아래와 같이 간단하게 값을 리턴하는 거라면 한 줄로 처리하는 것이 가독성이 더 좋습니다.
if (key === 'price_bucket') return obj[key].map((bucketId) => ({ price: PRICE_OPTION[bucketId] }))

// 위에서 key 가 price_bucket 이 아니면 무조건 아래로 빠집니다. 이것을 early return 패턴이라고 합니다.
// 따라서 else 문 안에 들어가던 로직을 그냥 아래와 같이 상단 레벨로 처리할 수 있습니다.
return modifiedObj[key].map((filterOption) => {
  const coffeesObj = {}

  coffeesObj.coffees = {
    // 이 정도 길이는 한 줄로 보는게 가독성이 좋은 것 같습니다.
    [key]: numberRgx.test(filterOption) ? Number(filterOption) : filterOption,
  }

  return coffeesObj
})
```

2020-11-08 10:22 UTC, mgm-dev commented on services/ProductService.js
> +  if (foundProduct.product_type === 'equipment') {
개행 추가했습니다 :)

2020-11-08 10:23 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +    }
:+1:

2020-11-08 10:23 UTC, mgm-dev commented on utils/makeDataForSort.js
> +}
감사합니다 :)

2020-11-08 10:24 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +  const numberRgx = /^\d+(\.\d+)?$/
`typeCaster`라는 모듈을 만들고, 해당 모듈 안에 `castIfInt`라는 함수를 만들어 봤습니다.

2020-11-08 10:53 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +  }
불필요한 else 문 삭제하고, 짧은 리턴 값을 한줄로 수정했습니다. 
추가적으로 3가지 사항을 수정했습니다.

- 커피 로스터의 이름으로 필터링 가능하게 수정
- 불필요한 변수 coffeeObj 사용하지 않게 수정
- try / catch 추가

2020-11-08 11:04 UTC, Jun4928 requested changes

2020-11-08 11:04 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +    if (key === 'price_bucket') obj[key].map((bucketId) => ({ price: PRICE_OPTION[bucketId] }))
여기 return 문 필요해 보입니다!

2020-11-08 11:04 UTC, Jun4928 commented on utils/typeCaster.js
> +module.exports = { castIfInt }
👍

2020-11-08 11:04 UTC, Jun4928 commented on utils/makeDataForFilter.js
> +    }
여기도 if 문 block 열지 않아도 됩니다.
```js
if (key === 'roasters') return obj[key].map ...
```

2020-11-08 13:51 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +    if (key === 'price_bucket') obj[key].map((bucketId) => ({ price: PRICE_OPTION[bucketId] }))
감사합니다 !!!!

2020-11-08 13:52 UTC, mgm-dev commented on utils/typeCaster.js
> +module.exports = { castIfInt }
🙏

2020-11-08 13:52 UTC, mgm-dev commented on utils/makeDataForFilter.js
> +    }
불필요한 block 제거 했습니다 :)

2020-11-08 14:00 UTC, Jun4928 commented
LGTM 🚀🔥

2020-11-08 14:00 UTC, merged