Add : Cart API
wecode-bootcamp-korea/13-coderoasters-backend pull request #4
Opened 2020-11-09 05:21 UTC by Daphne-dev

## Cart API 추가
- 장바구니 조회
- 장바구니 상품 추가
- 장바구니 상품 삭제
- 장바구니 상품 카운트 증가 & 감소

2020-11-09 14:37 UTC, Jun4928 requested changes
동현님! 리뷰 확인 및 반영 해 주세요 👍

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +    if (!cartItems) errorGenerator({ statusCode: 400, message: 'not found cart items'})
RESTFul API 규칙에 어긋납니다.
빈 카트인데 왜 400 에러 일까요? 

200 으로 처리하고, 빈 배열을 보내면 됩니다.

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +    if (!productId || !groundId || !quantity) errorGenerator({ statusCode: 400, message: 'invalid key error' })
에러처리 굿

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +  const order = await prisma.orders.findMany({
일단 이야기 나눈대로 Database 에 SQL 문을 수정하는거에 무리가 있을 수 있으니,
이 상태로 findMany 메소드를 쓴다고 가정하고 리뷰 남기도록 하겠습니다. 
(추후에 Prisma Schema 에서 unique 필드값 주셔서 리팩토링 해 주세요)

배열도 구조분해할당이 가능합니다. 첫번째 인자를 인덱스로 접근하는 것은 좋지 않습니다.
```js
const [order] = await prisma.orders.findMany({...})
```

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +  const order = await prisma.orders.findMany({
근데 지금 where 절로 들어가는 세가지 field 값들로
unique 한 조합을 만들어내지 못합니다. 그대로, findMany를 사용하셔도 될 것 같습니다. (`users:orders = 1:다` 이고, order_statuses 를 테이블의 다른 row 들도 공유하기 때문에)

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +  }, [])
새로운 배열을 만들어 내는 거라면 꼭 reduce 함수를 써야할까요?
map 함수로 동일한 일을 할 수 있습니다.
```js
const {order_products} = order
// map 함수는 인자에 콜백으로 넘겨준 함수를 실행시켜서 새로운 인자값을 얻어내고,
// 최종으로 같은 길이의 배열을 리턴합니다.
// 첫번째 인자로 들어가는 배열의 요소를 바로 구조분해할당 할 수 있습니다.
// 로직이 없이 바로 이렇게 값을 리턴할 때는 return 문이 없어도 됩니다.
// JavaScript 에서는 key 값에 string 처리를 해 줄 필요 없습니다.
return order_products.map(({ products, grounds }) => ({
    id: products.id,
    name: products.name,
    price: products.price,
    image: products.image,
    bagWeight: products.coffes.bag_weight,
    ground: {
      id: grounds.id,
      name: grounds.name
    }
  }))
```

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +    const cart = await CartService.findCartItems(userId)
같은 Service 로직을 타는데, 위는 cartItems, 여기는 cart 네요?

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +    if (!cartItems) errorGenerator({ statusCode: 400, message: 'not found cart items'})
또한 빈 배열에 부정연산을 한다고 해서 true 가 되지 않습니다.
true 값을 얻고 싶다면 다음과 같이 해야 합니다.
```js
!cartItems.length
```

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +    if (cart) {
CartService.findCartItems 는 항상 배열을 리턴하고 있습니다.
JavaScript 에서는 빈 배열도 truthy 한 값 입니다. 
따라서 항상 이 로직으로 빠지게 됩니다.

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +  const orders = await prisma.orders.findMany({
여기도 orders 구조분해 할당해서 아래서 사용하세요

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +  const orderProduct = await prisma.order_products.findMany({
이것도 구조분해 할당!

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +  if (orderProduct.length === 0) return prisma.order_products.create({
아래와 같이 true 를 얻어낼 수 있곘죠
```js
if (!orderProduct.length) 
```

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +
Early return pattern GOOD

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +const deleteProductCart = async (fields) => {
이 함수 내에서도 배열의 인덱스로 직접 접근하던 것들 모두 구조분해할당 해주세요

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +}
이 두 함수 하나로 합쳐보세요
나머지 로직은 똑같고
update 문 안에 들어가는 이 로직만 다르지 않나요?
```js
data: {
    quantity: { increment: 1 or -1 } 
}
```

2020-11-09 14:37 UTC, Jun4928 commented on services/CartService.js
> +  })
이 테이블에서는 
이 세가지 조합으로 분명 unique 한 값을 한 번에 찾아 낼 수 있겠네요.
그럼 update 함수 하나로 처리할 수 있을텐데요..

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +}
두개로 나누어진 controller(increaseProductCount, decreaseProductCount) 도 하나의 함수로 처리할 수 있겠네요.
body 에 action 을 하나 더 받으면 되지 않을까요? (더하는지, 빼는지)

ex) action 이 `increment` 또는 `decrement` 둘 중 하나로 오면 
아래 합쳐진 서비스 함수로 보내서 이 action 에 따라 quantity 를 증가 또는 감소 시키면 되겠네요.
```js


  return prisma.order_products.update({
    where: {
      id: orderProduct.id
    },
    data: {
      quantity: { [action]: 1 }
    }
  })
```

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +        id,
아래에서 userId 로 구조분해할당 하던데, id 를 그냥 넣어도 로직이 잘 돌아가나요?

2020-11-09 14:37 UTC, Jun4928 commented on controllers/CartController.js
> +    if (!cart) errorGenerator({ statusCode: 400, message: 'not found product'})
여기도 예외처리 하지 마세요. 
그리고 findCartItems 는 **배열**을 리턴하고 있습니다.

2020-11-10 02:16 UTC, Daphne-dev commented on controllers/CartController.js
> +    if (!cartItems) errorGenerator({ statusCode: 400, message: 'not found cart items'})
리뷰 감사합니다 !! 
너무 날코딩이어서 죄송해요...

2020-11-10 02:22 UTC, Daphne-dev commented on controllers/CartController.js
> +    if (!productId || !groundId || !quantity) errorGenerator({ statusCode: 400, message: 'invalid key error' })
감사합니다 :)

2020-11-10 04:40 UTC, Daphne-dev commented on services/CartService.js
> +  const order = await prisma.orders.findMany({
넵!

2020-11-10 04:40 UTC, Daphne-dev commented on services/CartService.js
> +  }, [])
수정했습니다 !

2020-11-10 04:44 UTC, Daphne-dev commented on services/CartService.js
> +
감사합니다 :)

2020-11-10 06:06 UTC, Daphne-dev commented on controllers/CartController.js
> +    const cart = await CartService.findCartItems(userId)
해당 부분 완전히 수정했습니다 ㅠㅠ

2020-11-10 06:35 UTC, Daphne-dev commented on services/CartService.js
> +  if (orderProduct.length === 0) return prisma.order_products.create({
수정했습니다 :)

2020-11-10 07:52 UTC, Daphne-dev commented on services/CartService.js
> +  })
세가지 컬럼들이 unique 한 필드이긴 하지만 update 로는  unique한 컬럼만 사용할수 있어서
updateMany 로 대체하였습니다 :)

2020-11-10 07:55 UTC, Daphne-dev commented on controllers/CartController.js
> +        id,
해당 부분 로직 수정하였습니다 !

2020-11-10 07:56 UTC, Daphne-dev commented on controllers/CartController.js
> +    if (!cart) errorGenerator({ statusCode: 400, message: 'not found product'})
빈 배열 리턴하도록 변경하였습니다

2020-11-10 08:00 UTC, Daphne-dev commented on controllers/CartController.js
> +}
와 .. 이런 신박한 방법이 있다니 이런식으로 처리할 수 도 있다는 것에 감탄했어요 덕분에 코드가 간결해진 거 같아요

2020-11-10 08:00 UTC, Daphne-dev commented on services/CartService.js
> +}
수정했습니다 :)

2020-11-10 10:33 UTC, Jun4928 commented
LGTM 🚀🤘

2020-11-10 10:33 UTC, merged